name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_pgsql

      - name: Install dependencies
        working-directory: ./src
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        working-directory: ./src
        run: php artisan test

      - name: Build Docker image
        run: docker build -t laravel-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker tag laravel-app:latest ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest && docker push ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/laravel
            docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
            docker compose down
            docker compose up -d
            docker exec laravel-app php artisan migrate --force
